#!/usr/bin/guile
!#

; todo: thumbnails, itml convert, csv convert, atom feed, upload, configurable theme/layout, copy sources

(import (sph) (sph cli)
  (sph lang plcss) (ice-9 ftw)
  (sph string) (sph lang scheme)
  (sxml simple) (sph lang sescript)
  (sph list) (sph one)
  ;(sph web publish itml)
  (sph process) (sph alist) (sph hashtable) (sph vector) (sph lang config) (sph filesystem))

(define program-description
  "sph-web-publish management utility
   features
     preprocess source files
     copy source files into subdirectory near compiled file
     create thumbnails for images")

(define swp-env-root (vector-accessor 1))
(define swp-env-config (vector-accessor 2))
(define swp-env-data-root (vector-accessor 3))
(define swp-env-file-handlers (vector-accessor 4))
(define swp-env-copy (vector-accessor 5))
(define swp-file-handler-suffix (vector-accessor 0))
(define swp-file-handler-f (vector-accessor 1))
(define (swp-file-handler-new suffix f) (vector suffix f))

(define default-config
  (ht-create-symbol-q data-root "data/"
    sources-directory-name "sources"
    use-hardlinks #t start "start.html" thumbnail-size 100 feed-rights "creative commons by-nc"))

(define swp-file-handlers
  (list (swp-file-handler-new "itml" (l (env path target-path) #t))
    (swp-file-handler-new ".plcss"
      (l (env path target-path)
        (let (data (file->datums path))
          (call-with-output-file (string-append (string-drop-suffix ".plcss" target-path) ".css")
            (l (port) (plcss->css data port))))))
    (swp-file-handler-new ".sxml"
      (l (env path target-path)
        (let (data (file->datums path))
          (call-with-output-file (string-append (string-drop-suffix ".sxml" target-path) ".xml")
            (l (port) (sxml->xml data port))))))
    (swp-file-handler-new ".shtml"
      (l (env path target-path)
        (let (data (file->datums path))
          (call-with-output-file (string-append (string-drop-suffix ".shtml" target-path) ".html")
            (l (port) (display "<!doctype html>" port) (sxml->xml data port))))))
    (swp-file-handler-new ".sjs"
      (l (env path target-path)
        (let (data (file->datums path))
          (call-with-output-file (string-append (string-drop-suffix ".sjs" target-path) ".js")
            (l (port) (sescript->ecmascript data port))))))
    (swp-file-handler-new (list ".png" ".jpeg" ".jpg")
      (l (env path target-path)
        (let*
          ( (dir (string-append (ensure-trailing-slash (dirname path)) "thumbnails"))
            (target (string-append dir (basename path))))
          (if (file-exists? target)
            (if (> (stat:mtime (stat path)) (stat:mtime (stat target))) #t #t)
            (and (ensure-directory-structure dir) #t)))))
    (swp-file-handler-new (list ".itml" ".plcss" ".shtml" ".sjs" ".sxml")
      (l (env path target-path)
        (let*
          ( (copy (swp-env-copy env))
            (sources-directory-name (ht-ref-q (swp-env-config env) sources-directory-name))
            (target-dir (string-append (dirname target-path) sources-directory-name)))
          (and (ensure-directory-structure target-dir)
            (copy path (string-append (ensure-trailing-slash target-dir) (basename target-path)))))))
    (swp-file-handler-new #t (l (env path target-path) ((swp-env-copy env) path target-path)))))

(define (program-path)
  "-> string
   return the full-path of the currently executed program file. uses the first argument of (program-arguments)"
  (let (part (first (program-arguments)))
    (if (string-null? part) part
      (if (eqv? #\/ (string-ref part 0)) part (string-append (getenv "PWD") "/" part)))))

(define (swp-file-handlers-normalise a)
  (map
    (l (a)
      (swp-file-handler-new
        (let (suffix (swp-file-handler-suffix a))
          (cond
            ((string? suffix) (l (path) (string-suffix? suffix path)))
            ((list? suffix) (l (path) (any (l (a) (string-suffix? a path)) suffix)))
            ((procedure? suffix) suffix)
            ((boolean? suffix) (const suffix))
            (else (raise (q invalid-file-handler-suffix)))))
        (swp-file-handler-f a)))
    a))

(define (swp-config-get-file root name) "string string -> hashtable"
  (let*
    ( (default-path (string-append root "config/default.scm"))
      (config
        (or (and (file-exists? default-path) (config-read-file default-path)) (ht-create-symbol)))
      (name-config
        (and (not (string-equal? "default" name))
          (config-read-file (string-append root "config/" name ".scm")))))
    (if name-config (ht-tree-merge! config name-config)) config))

(define (swp-config-get root config)
  (let (a (ht-copy default-config #t))
    (ht-tree-merge! a
      (if (string? config) (swp-config-get-file root config) (or config (ht-create-symbol))))
    a))

(define (swp-file-system-for-each f file-name) "procedure string:path -> boolean"
  (let
    ( (leaf (l (name stat result) (and result (f name stat))))
      (enter? (l (name stat result) result)) (ignore (l (name stat result) result))
      (error
        (l (name stat errno result)
          (format (current-error-port) "warning: ~a: ~a~%" name (strerror errno)) #f)))
    (file-system-fold enter? leaf ignore ignore ignore error #t file-name)))

(define (swp-thumbnails-env-new data-root thumbnails-root size)
  (let
    ( (gm-path (first-or-false (search-env-path (list "gm"))))
      (size-string (string-append "x" (number->string size) "x"))
      (destination-path
        (l (path) (string-append thumbnails-root (string-drop-prefix-if-exists data-root path)))))
    (vector (q thumbnails-env)
      (l (path)
        (debug-log execute gm-path
          "convert" "-size"
          size-string path
          "-resize" size-string "+profile" "*" (string-append "jpeg:" (destination-path path)))))))

(define (swp-env-new options)
  (alist-bind options (config)
    (let*
      ( (root
          (ensure-trailing-slash
            (realpath* (string-trim-right (dirname (dirname (program-path))) #\.))))
        (config (swp-config-get root (or (alist-ref-q options config) "default")))
        (data-root (string-append root (ensure-trailing-slash (ht-ref-q config data-root))))
        (copy (if (ht-ref-q config use-hardlinks) link copy-file)))
      (vector (q swp-env) root
        config data-root (swp-file-handlers-normalise swp-file-handlers) copy))))

(define (swp-compile env options)
  (let
    ( (source-dir (swp-env-data-root env))
      (target-dir (string-append (swp-env-root env) "compiled/"))
      (file-handlers (swp-env-file-handlers env)))
    (swp-file-system-for-each
      (l (path stat-info)
        (and-let*
          ((handler (any (l (a) (and ((swp-file-handler-suffix a) path) a)) file-handlers)))
          (let*
            ( (relative-path (string-drop-prefix source-dir path))
              (target-path (string-append target-dir relative-path))
              (target-path-dir (ensure-trailing-slash (dirname target-path))))
            (and (ensure-directory-structure target-path-dir)
              (or
                (and (file-exists? target-path)
                  (>= (stat:mtime (stat target-path)) (stat:mtime stat-info)))
                ((swp-file-handler-f handler) env path target-path))))))
      (remove-trailing-slash source-dir))))

(define (swp-upload env options) #t
  ;(list execute "rsync" data-root target)
  )

(define (swp-compile-and-upload env options)
  (and (swp-compile env options) (swp-upload env options)))

(define (cli-command-handler command options) "(string ...) list ->"
  (apply
    (l (a)
      ( (string-case a ("compile" swp-compile)
          ("upload" swp-upload) ("compile-and-upload" swp-compile-and-upload)
          (else (display-line (q invalid-command)) (exit 1)))
        (swp-env-new options) options))
    command))

(define cli
  (cli-create #:about program-description
    #:options (list-q ((command argument ...)))
    #:command-handler cli-command-handler
    #:commands
    (list-qq (("compile") ((config)) #:description "update all files under data/")
      (("upload") ((config)) #:description "update files on the configured server")
      (("compile-and-upload") ((config)) #:description "compile and on success upload"))))

(define (swp-cli) (if (null? (tail (program-arguments))) (cli (list "--help")) (cli)))
(swp-cli)
